baseURL = "https://sooyoungro.github.io/"
metaDataFormat = "yaml"
title = "Sooyoungro Church"
theme = "blist"

DefaultContentLanguage = "ko"
DefaultContentLanguageInSubdir = true

[languages]
  [languages.ko]
    contentDir = "content/ko"
    weight = 1
    languageName = "한국어(Korean)"
  [languages.ko.params]
    introTitle = "한국어(Korean)"
    introSubtitle = "한국어 영상 모음입니다."
    introPhoto = "/flag_korea.png"
  [[languages.ko.menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - 수영로교회 국제사역국 통번역팀 · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-indigo-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = false

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = true

# [params.homepage.social]
#   # Global params common for both languages
#   title = "Follow me"
#   description = "I work on everything coding and tweet developer memes"

#   [[params.homepage.social.icons]]
#     website = "youtube"
#     url = "https://www.youtube.com/@sooyoungrochurch7718"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
